### PR TITLE
Use strings builder

### PR DESCRIPTION
**Pull request by ninedraft**
Hello! I'm suggesting to use the [strings.Builder](https://golang.org/pkg/strings/#Builder) instead of [bytes.Buffer](https://golang.org/pkg/bytes/#Buffer). It's a more efficient alternative with very low cast costs.

### CODE REVIEW

**Comment by huandu** [comment]
`strings.Builder` is available since go1.10. It can be a break change for packages or projects importing this package.

Please consider to implement a helper builder which calls `strings.Builder` if it's available and uses `bytes.Buffer` as a fallback.

**Comment by ninedraft** [comment]
> `strings.Builder` is available since go1.10. It can be a break change for packages or projects importing this package.
> 
> Please consider to implement a helper builder which calls `strings.Builder` if it's available and uses `bytes.Buffer` as a fallback.

done ✅

**Comment by huandu** [comment]
Very cool! Thank you.

I have several comments on filenames of the newly added files.

* According to Go best practice, when we need to build code for specific Go version, we should add version as suffix in a name like `buffer_go110.go`. Therefore, `buffer.go` and `buffer_old.go` should be renamed as `buffer_go110.go` and `buffer.go` respectively.
* Filename should be consistence with type name. The `buffer` is not a right name as the type defined in this file is `bufferString`. BTW, I think it would be better to name the type as `stringBuilder` and the file as `stringbuilder.go`.

**Comment by ninedraft** [comment]
> Very cool! Thank you.
> 
> I have several comments on filenames of the newly added files.
> 
>     * According to Go best practice, when we need to build code for specific Go version, we should add version as suffix in a name like `buffer_go110.go`. Therefore, `buffer.go` and `buffer_old.go` should be renamed as `buffer_go110.go` and `buffer.go` respectively.
> 
>     * Filename should be consistence with type name. The `buffer` is not a right name as the type defined in this file is `bufferString`. BTW, I think it would be better to name the type as `stringBuilder` and the file as `stringbuilder.go`.

done ✅

**Pull request merged**
