### PR TITLE
Added code to run PowerSystems

### PR DESCRIPTION
**Pull request by genisysram**
Hi,
This is my contribution to your code to make it work on PowerSystems.

Thanks for the code, its working good.
## What do these changes do?
Added Architecture "ppc64le"
## Are there changes in behavior for the user?
No

### CODE REVIEW

**Comment by huandu** [comment]
There is no arch specific code in this package. I don't think it's necessary to modify travis config. I'll close this PR.

Thanks for your PR anyway. Welcome to do more contribution in future.

**Comment by genisysram** [comment]
This also ensures that whatever versions of go you are using is complete and supports all features on ppc64le. And, it is possible for go programs to be architecture dependent - if someone ever adds a dependency on the hardware, expected or not, this will ensure that the project will always build when it gets to the distros - if not, the distro porting team winds up picking up the work which can be painful to those coming in from outside the project.

**Comment by huandu** [comment]
I don't think it's reasonable for an arch-independent package to test against a specific arch. Even if Go compiler drops support to ppc64le for some reasons, this package should still work fine on all supported archs. In this case, tests on Travis CI should be passed rather than failed.

**Comment by genisysram** [comment]
Tagging @gerrith3

**Pull request closed without merging**
